version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: VgSLDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./datasets:/datasets
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://postgres:admin@postgres:5432/VgSLDB
    volumes:
      - ./backend:/home/node/app
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    command: npm run dev
    restart: always

  frontend:
     build: ./frontend
     environment:
       - REACT_APP_BACKEND_URL=http://backend:5000
     volumes:
       - ./frontend:/react-docker-example
     ports:
       - "3000:3000"
     depends_on:
       - backend

  importer:
    build: ./import
    environment:
      - RUN_IMPORT=false
      - DATABASE_URL=postgres://postgres:admin@postgres:5432/VgSLDB
    volumes:
      - ./import/datasets:/app/datasets
      - ./data:/data
    command: sleep 1000000
    depends_on: 
      - postgres

volumes:
  pgdata: