version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: VgSLDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./datasets:/datasets
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://postgres:admin@postgres:5432/VgSLDB
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    command: node, index.js

  frontend:
    build: ./frontend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
    ports:
      - "3000:80"
    depends_on:
      - backend

  importer:
    build: ./import
    command: sleep 10000
    environment:
      - RUN_IMPORT=false
      - DATABASE_URL=postgres://postgres:admin@postgres:5432/VgSLDB
    volumes:
      - ./import/datasets:/app/datasets
      - ./data:/data
    depends_on: 
      - postgres

volumes:
  pgdata: